import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import MainContainer from "@src/components/MainContainer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dooper</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/assets/logo-dooper.png"
          key="icon16"
        />
      </Head>

      <main>
        <MainContainer>
          <h1>Welcome to</h1>
          <Image
            src="/_next/image?url=%2Fassets%2Flogo-dooper.png&w=384&q=75"
            alt="dooper"
            width="200px"
            height="100px"
          />
        </MainContainer>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
